[package]
name = "nitro_repo"
version = "0.1.0"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.7", features = ["mysql", "r2d2"] }
diesel_migrations = "1.4.0"
r2d2 = "0.8.9"
r2d2_mysql = "*"
dotenv = "0.15.0"
actix = "0.11"

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.64"
serde_qs = "0.8.4"
zip = "0.5.13"
futures = "0.3.17"
sanitize-filename = "0.3"
actix-files = "0.5.0"
env_logger = "0.9"
rand = "0.8.4"
futures-util = "0.3.17"
actix-web = {version = "3.3.2",features = ["openssl"] }
openssl = { version = "0.10", features = ["v110"] }
log4rs = "1.0.0"
log = "0.4.14"
strum = { version = "0.21.0", features = ["derive"] }
strum_macros = "0.21.1"
derive_more = "0.99.14"
chrono = "0.4.19"
hyper = "0.14.11"
hyper-tls = "0.4.3"
time = "0.3.2"
actix-multipart = "0.3.0"
actix-session = "0.4.1"
actix-cors = "0.5.4"
lazy-static-include = "3.1.1"
toml="0.5.8"
lazy_static = "1.4.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
argon2 = "0.3.0"
rand_core = { version = "0.6.3", features = ["std"] }
lettre = "0.10.0-rc.3"
rust-embed = {version="6.2.0", features=["interpolate-folder-path"]}
handlebars = "4.1.0"
serde_yaml = { version = "0.8.20" }
tera = "1.12.1"
base64 = "0.13.0"